//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A108222027_finalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tAccount
    {
        public string aAcount { get; set; }
        public string aPassword { get; set; }
        public string aHead { get; set; }
        public int aLevel { get; set; }
        public int aPhone { get; set; }
        public string aAddress { get; set; }
        public int aSeq { get; set; }
        public string Transaction { get; set; }
    }
}
