//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A108222027_finalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tdiscount
    {
        public int Id { get; set; }
        public string Discount { get; set; }
        public Nullable<decimal> money { get; set; }
        public Nullable<int> noob { get; set; }
        public string discribe { get; set; }
        public Nullable<int> limit { get; set; }
    }
}
